TECHCRUNCH_TOPICS = {
    "AI": "category/artificial-intelligence/",
    "Amazon": "tag/amazon/",
    "Apps": "category/apps/",
    "Biotech & Health": "category/biotech-health/",
    "Climate": "category/climate/",
    "Cloud Computing": "tag/cloud-computing/",
    "Commerce": "category/commerce/",
    "Crypto": "category/cryptocurrency/",
    "Enterprise": "category/enterprise/",
    "EVs": "tag/evs/",
    "FinTech": "category/fintech/",
    "Fundraising": "category/fundraising/",
    "Gadgets": "category/gadgets/",
    "Gaming": "category/gaming/",
    "Google": "tag/google/",
    "Government & Policy": "category/government-policy/",
    "Hardware": "category/hardware/",
    "Instagram": "tag/instagram/",
    "Layoffs": "tag/layoffs/",
    "Media & Entertainment": "category/media-entertainment/",
    "Meta": "tag/meta/",
    "Microsoft": "tag/microsoft/",
    "Privacy": "category/privacy/",
    "Robotics": "category/robotics/",
    "Security": "category/security/",
    "Social": "category/social/",
    "Space": "category/space/",
    "Startups": "category/startups/",
    "Transportation": "category/transportation/",
    "Venture": "category/venture/",
}

PERSONAS = [
    "AI Engineer",
    "ML Engineer",
    "AI Researcher",
    "ML Researcher",
    "Data Scientist",
    "Data Analyst",
    "Software Engineer",
    "Product Manager",
    "Startup Founder",
    "FinTech Expert",
    "Stock Market Analyst",
    "University Professor",
    "PhD Student",
    "Master's Student",
    "Undergraduate Student",
    "High School Student",
]

SOURCES= [
    "TechCrunch",
]